[package]
name = "rusty_socks"
version = "0.0.1"
authors = ["Aaron Roney <twitchax>"]
edition = "2018"

[dependencies]
rand = "0.7.2"
net2 = "0.2.33"
futures = "0.3.1"
pnet = "0.23.0"
toml = "0.5.5"
serde = { version = "1.0.104", features = ["derive"] }
tokio = { version = "0.2.4", features = ["full"] }